name: Docker Build and Push

on:
  push:
    branches:
      - nightly

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dannicool
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t dannicool/docker-wechatbot-webhook:nightly
          docker push dannicool/docker-wechatbot-webhook:nightly
